name: Code Coverage

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm run test:coverage -- --json --outputFile="coverage/coverage-report.json"

      - name: Jest Coverage Comment
        uses: ArtiomTr/jest-coverage-report-action@v2.3.0
        with:
          skip-step: all
          annotations: none
          coverage-file: coverage/coverage-report.json
          base-coverage-file: coverage/coverage-report.json
