name: Code Coverage

on:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Jest Annotations & Coverage
        uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
