name: Code Coverage 2

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.3

      - name: Use Node.js @v4.0.2
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 21
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Run tests
        run: npm test

      - name: Jest Coverage Comment
        uses: ArtiomTr/jest-coverage-report-action@v2.3.0
